### ISSUE TITLE
Add more colors in dropdown section

### ISSUE THREAD

**Issue by vishal-codes** [vishal-codes/react-widgets#1]
As of now the Dropdown section of the project only supports two colors (Blue and Yellow). We can add more colours.
Before making changes please make sure that you have completed steps till [Branching](https://github.com/vishal-codes/react-widgets/blob/main/CONTRIBUTING.md#branching).

#### Steps for adding more colours 
1.  change the directory from present to the `src/data/colorOptions.js` file.
2. now edit the array named [colorOptions ](https://github.com/vishal-codes/react-widgets/blob/886ff877c86985311fadfcb2626f6146252bfa38/src/data/colorOptions.js#L1) by adding a new item and assign the `label` and `value` with the colour name (please follow the casing)
3. save the changes and [commit](https://github.com/vishal-codes/react-widgets/blob/main/CONTRIBUTING.md#commiting-changes)

#### List of colour's to be added (NOTE: You don't need to add all the colours, just add one or two colour's. Not more than two.)
- [x] AntiqueWhite
- [x] Aqua
- [x] Aquamarine
- [x] Blue
- [x] BlueViolet
- [x] Brown
- [x] CadetBlue
- [x] Chartreuse
- [x] Chocolate
- [x] Coral
- [x] CornflowerBlue
- [x] Crimson
- [x] Cyan
- [x] DarkBlue
- [x] DarkCyan
- [x] DarkGoldenRed
- [x] DarkGray
- [x] DarkGreen
- [x] DarkKhaki
- [x] DarkMagenta
- [x] DarkOliveGreen
- [x] DarkOrange
- [x] DarkOrchid
- [x] DarkRed
- [x] DarkTurquoise
- [x] DarkViolet
- [x] DeepPink
- [ ] DeepSkyBlue
- [x] DimGray
- [ ] DodgerBlue
- [ ] ForestGreen
- [x] Fuchsia
- [x] Gold
- [x] Green
- [ ] GreenYellow
- [x] HotPink
- [ ] IndianRed 
- [ ] Indigo 
- [x] Khaki
- [x] Lavender
- [x] LightBlue
- [x] LightCoral
- [ ] LightGreen
- [x] LightPink
- [x] LightSalmon
- [x] LightSeaGreen
- [x] Lime
- [ ] Linen
- [ ] Magenta
- [x] Maroon
- [ ] MediumBlue
- [ ] MidnightBlue
- [x] NavajoWhite
- [x] Olive
- [x] OrangeRed
- [x] Orchid
- [x] PaleGreen
- [x] PaleVioletRed
- [x] Peru
- [x] Pink
- [x] Plum
- [x] Purple
- [x] Red
- [x] SandyBrown
- [ ] Silver
- [ ] Snow
- [x] Tomato
- [ ] Turquoise
- [x] Violet
- [ ] WhiteSmoke
- [x] Yellow
- [ ] YellowGreen

**Comment by Ayushi7456** [comment]
I would like to work on this.

**Comment by vishal-codes** [comment]
> I would like to work on this if it's a part of Hacktoberfest.

Yes @Ayushi7456 please go ahead! 👍

**Comment by Vidushi-Gupta** [comment]
Hi, could you please assign me this for hacktoberfest?

**Comment by vishal-codes** [comment]
> Hi, could you please assign me this for hacktoberfest?

Yes @Vidushi-Gupta  please go ahead 👍 . Add any one color👍

**Comment by Amiyanshu-web** [comment]
Can I add a color

**Comment by Vidushi-Gupta** [comment]
> > Hi, could you please assign me this for hacktoberfest?
> 
> Yes @Vidushi-Gupta please go ahead 👍 . Add any one color👍

Just added a PR. Thank you!

**Comment by OmDharme** [comment]
Can I work on this?

**Comment by Sejal-16** [comment]
will this pull request count towards hacktober fest

**Comment by 2201monesh** [comment]
HHey @vishal-codes I have raised a PR #30 can you give it a hacktoberfest label

**Comment by vishal-codes** [comment]
> will this pull request count towards hacktober fest

No at that time I wasn't able to add the labels, Now the labels are available if u make a new with new changes then I can give ur pr a label 🚀

**Comment by vishal-codes** [comment]
> Hey @vishal-codes I have raised a PR #30 can you give it a hacktoberfest label

yaa sure

**Comment by hellodeborahuk** [comment]
Can I do one colour please?

**Comment by sakshamgurbhele** [comment]
> Can I do one colour please?

Go ahead

**Comment by ayangupta9** [comment]
Hi! May I add a color too?

**Comment by sakshamgurbhele** [comment]
> Hi! May I add a color too?

Sure, Go ahead @ayangupta9

**Comment by Atharv777** [comment]
Hi @vishal-codes I have added DarkOrange and DarkOliveGreen color please merge my PR #58 . Thank you

**Comment by alceil** [comment]
Can i work on this issue?

**Comment by Abhiram970** [comment]
Added IndianRed and LightBlue colours :D

**Comment by copyNinja1219** [comment]
added Green color : ) #70

**Comment by ShubhamManna** [comment]
added Cyan color in dropdown #75

**Comment by sauloviniciusf** [comment]
adding Blue Violet color https://github.com/vishal-codes/react-widgets/pull/77

**Comment by gefymarcos** [comment]
adding Silver color #79

**Comment by arthur322** [comment]
Added the Dark Salmon color #80

**Comment by danielphilipjohnson** [comment]
Added the color Peru [#84](https://github.com/vishal-codes/react-widgets/pull/84 )

**Comment by sofiarm21** [comment]
Hi! Can I work on this ?

**Comment by Dhananjaymahajan2001** [comment]
Hello I added color LightSeaGreen to App.js #87    Please merge this pr

**Comment by Dhananjaymahajan2001** [comment]
closes #87

**Comment by sofiarm21** [comment]
Hi, I added color LightSalmon #85

**Comment by 2201monesh** [comment]
Hi added Crimson color take a look #88

**Comment by amanrk28** [comment]
Hi! I'd like to work on this as a beginner open-source contributor. Can you please assign this issue to me?

**Comment by wh1zk1d** [comment]
Hey, I added HotPink: #95

**Comment by sauloviniciusf** [comment]
> adding Blue Violet color #77

@vishal-codes 

I closed this one, cause a refactor was made with how colors options are defined, and on this refactor the color I originally addeed was added too. So, I added another one :) `CornflowerBlue`.

https://github.com/vishal-codes/react-widgets/pull/102

**Comment by flushstriker** [comment]
I would like to contribute to this issue

**Comment by MOHAMMEDAFEEF** [comment]
4 colors are added #119

**Comment by sadathshariff** [comment]
Hi @vishal-codes I have added 2 Colors and 2 languages #118  Please Look into it

**Comment by sakshamgurbhele** [comment]
Lovely people, it will be a little easy for Maintainers if you do not link this issue! It is getting close whenever we are merging a PR. 

ヽ(^o^)丿
Happy Open-Source.

**Comment by thunderfreak** [comment]
hey, one of my prs have already been merged (which added 2 languages). Can I still contribute on this issue?

**Comment by sakshamgurbhele** [comment]
> hey, one of my prs have already been merged (which added 2 languages). Can I still contribute on this issue?

Yeah, why not

**Comment by sadathshariff** [comment]
Hi, @vishal-codes  i would like to add MediumBlue
 MidnightBlue can you please assign this to me

**Comment by sakshamgurbhele** [comment]
> Hi, @vishal-codes i would like to add MediumBlue MidnightBlue can you please assign this to me

Hey @sadathshariff, you can open a PR. no worries
