### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Soham2020** [vishal-codes/react-widgets#122]
Hi @vishal-codes .
I want to add a basic react form.

Preview of the form is below:

![Screenshot (103)](https://user-images.githubusercontent.com/66131928/135761620-06b6de44-bbf1-483d-8d49-32d9888e4e8b.png)

Please kindly assign this issue.
Thanks

**Comment by Soham2020** [comment]
@vishal-codes , plz assign this issue, so that I could work on it as soon as possible.

**Comment by vishal-codes** [comment]
> @vishal-codes , plz assign this issue, so that I could work on it as soon as possible.

Sorry @Soham2020 but i don't think we need any more features
