### ISSUE TITLE
Add Text Editor Widget

### ISSUE THREAD

**Issue by swapnil0709** [vishal-codes/react-widgets#123]
Hi, @vishal-codes @sakshamgurbhele I want to add a new widget that will be a text editor component. I have made the basic design and I'm yet to theme it to match your theme. But before that, I want to confirm if you are good with creating this issue and me working on this one?

Please feel free to share your thoughts on this and let me know if we can give it a tag of hacktober fest so that it will be considered.

![image](https://user-images.githubusercontent.com/23692968/135762556-1cfb28cc-770b-44eb-ab23-83c36e0510b3.png)

**Comment by vishal-codes** [comment]
> Hi, @vishal-codes @sakshamgurbhele I want to add a new widget that will be a text editor component. I have made the basic design and I'm yet to theme it to match your theme. But before that, I want to confirm if you are good with creating this issue and me working on this one?
> 
> Please feel free to share your thoughts on this and let me know if we can give it a tag of hacktober fest so that it will be considered.
> 
> ![image](https://user-images.githubusercontent.com/23692968/135762556-1cfb28cc-770b-44eb-ab23-83c36e0510b3.png)

Yes @swapnil0709 Please go ahead with your work and please make another folder for styles and also this feature should be mobile responsive :) ATB
