### ISSUE TITLE
Refactoring Project Structure

### ISSUE THREAD

**Issue by rizastoday** [vishal-codes/react-widgets#24]
Hi @vishal-codes , may I help a bit to make project structure more maintainable? I will move some file to separate folder to make the project structure more clear and easy to maintain, I'am on my learning too let's learn together :D, thanks

**Comment by vishal-codes** [comment]
> Hi @vishal-codes , may I help a bit to make project structure more maintainable? I will move some file to separate folder to make the project structure more clear and easy to maintain, I'am on my learning too let's learn together :D, thanks

Okay but lets first discuss about ur plan

**Comment by rizastoday** [comment]
Maybe I will create some folder and move some to that folder separately. Like Routes folder for example so u can focus on what u edit without getting confuse with other files

**Comment by rizastoday** [comment]
Or maybe I will move some components to separate folder module and it's css separately too ?

**Comment by rizastoday** [comment]
this is what im doing so far:

![image](https://user-images.githubusercontent.com/44855641/135585621-53e88627-c839-4af3-b85e-3e8d15e311f5.png)

**Comment by rizastoday** [comment]
This is what im doing so far:

![Capture](https://user-images.githubusercontent.com/44855641/135586009-9218ae6c-5038-4f35-89b2-1aeac67877e6.PNG)

**Comment by rizastoday** [comment]
This is what im doing so far, by making folder separately you won't be confused again when this project grow bigger

![image](https://user-images.githubusercontent.com/44855641/135588288-f7a32df5-9a56-4ba8-aec7-17d4d9765c49.png)

**Comment by vishal-codes** [comment]
> Maybe I will create some folder and move some file to that folder separately. Like Routes folder for example so u can focus on what u edit without getting confuse with other files

that's great idea please open a pr I'll inspect the changes and will merge it if everything works fine.

**Comment by rizastoday** [comment]
Hi I've just make a pr for this issue, hope you will approve it :D let me know if it has any mistake or something wrong

**Comment by vishal-codes** [comment]
> Hi @vishal-codes I've just make a pr for this issue, hope you will approve it :D let me know if it has any mistake or something wrong

Hey I saw your PR, thank you very much for the changes. I have closed the issue for the time being because ur branch have complex merge  conflicts which I have to solve locally, so till then I keep this issue as closed.

**Comment by vishal-codes** [comment]
Thank You @rizastoday
