### ISSUE TITLE
Add React Themes

### ISSUE THREAD

**Issue by Soham2020** [vishal-codes/react-widgets#67]
Hi @vishal-codes .
I want to add a multiple theme switching widget.

**Comment by sakshamgurbhele** [comment]
Sure, Go ahead! @Soham2020

**Comment by vishal-codes** [comment]
> Hi @vishal-codes . I want to add a multiple theme switching widget.

If you want to add then please make sure that you don't add it on the navbar. Place the theme toggler somewhere else.

**Comment by sakshamgurbhele** [comment]
We could merge that into a new branch if not what we wanted @vishal-codes

**Comment by Soham2020** [comment]
Ok @vishal-codes, will place somewhere else.

**Comment by vishal-codes** [comment]
> We could merge that into a new branch if not what we wanted @vishal-codes

Yaa we could do that, but I just wanted to make it clear about how I want or else soham's time would have been wasted if he had putted the option of `toggle-theme` on nav-bar.

**Comment by sakshamgurbhele** [comment]
Awesome 👍🏼

**Comment by vishal-codes** [comment]
@Soham2020 Can we implement  [this](http://vakila.github.io/) . Click that button on the site.
![Screenshot 2021-10-02 133833](https://user-images.githubusercontent.com/79784161/135708825-ace3a5da-0fc4-4d77-9557-ffb70406d802.jpg)

**Comment by Soham2020** [comment]
Let me first do toggle theme, then I will try it

**Comment by vishal-codes** [comment]
> Let me first do toggle theme, then I will try it

Ya I don't want that feature as it I was suggesting that can we have a button like that on the page and when we click on it it just toggle themes and I don't want 3 or 5 themes just light and dark mode will be great! All the best, **also the project structure is refactored.**

**Comment by Soham2020** [comment]
Ya ya, there will be a toggle button for light and dark mode

**Comment by vishal-codes** [comment]
> Ya ya, there will be a toggle button for light and dark mode

Great

**Comment by Soham2020** [comment]
Hi @vishal-codes ..
Facing problem regarding bg color switching, so I am closing this issue.
Sorry inconvenience.
